### main page
GET http://localhost:3000/

### test post rwquest to /user
Post http://localhost:3000/user
Content-Type: application/json

{
    "username": "Alice",
    "age": 30,
    "email": "alice@example.com"
}

### pie test
GET  http://localhost:3000/applepie/1

### fly test
GET http://localhost:3000/.Pigs_Can_fly

### class time
GET http://localhost:3000/classTime/7:30am-10:30am